/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ShareGuestListIndexRouteImport } from './routes/share-guest-list/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareGuestListEventIdRouteImport } from './routes/share-guest-list/$eventId'
import { Route as AuthVerifyResetPasswordRouteImport } from './routes/auth/verify-reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCreatePasswordRouteImport } from './routes/auth/create-password'
import { Route as AuthBusinessInfoRouteImport } from './routes/auth/business-info'
import { Route as AuthenticatedEventIdRouteImport } from './routes/_authenticated/$eventId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedSettingsPlanBillingsRouteImport } from './routes/_authenticated/settings/plan-billings'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareGuestListIndexRoute = ShareGuestListIndexRouteImport.update({
  id: '/share-guest-list/',
  path: '/share-guest-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShareGuestListEventIdRoute = ShareGuestListEventIdRouteImport.update({
  id: '/share-guest-list/$eventId',
  path: '/share-guest-list/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyResetPasswordRoute = AuthVerifyResetPasswordRouteImport.update({
  id: '/auth/verify-reset-password',
  path: '/auth/verify-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreatePasswordRoute = AuthCreatePasswordRouteImport.update({
  id: '/auth/create-password',
  path: '/auth/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBusinessInfoRoute = AuthBusinessInfoRouteImport.update({
  id: '/auth/business-info',
  path: '/auth/business-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventIdRoute = AuthenticatedEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPlanBillingsRoute =
  AuthenticatedSettingsPlanBillingsRouteImport.update({
    id: '/settings/plan-billings',
    path: '/settings/plan-billings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$eventId': typeof AuthenticatedEventIdRoute
  '/auth/business-info': typeof AuthBusinessInfoRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-reset-password': typeof AuthVerifyResetPasswordRoute
  '/share-guest-list/$eventId': typeof ShareGuestListEventIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/share-guest-list': typeof ShareGuestListIndexRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/plan-billings': typeof AuthenticatedSettingsPlanBillingsRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/$eventId': typeof AuthenticatedEventIdRoute
  '/auth/business-info': typeof AuthBusinessInfoRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-reset-password': typeof AuthVerifyResetPasswordRoute
  '/share-guest-list/$eventId': typeof ShareGuestListEventIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/share-guest-list': typeof ShareGuestListIndexRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/plan-billings': typeof AuthenticatedSettingsPlanBillingsRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/$eventId': typeof AuthenticatedEventIdRoute
  '/auth/business-info': typeof AuthBusinessInfoRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-reset-password': typeof AuthVerifyResetPasswordRoute
  '/share-guest-list/$eventId': typeof ShareGuestListEventIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/share-guest-list/': typeof ShareGuestListIndexRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/plan-billings': typeof AuthenticatedSettingsPlanBillingsRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$eventId'
    | '/auth/business-info'
    | '/auth/create-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-reset-password'
    | '/share-guest-list/$eventId'
    | '/'
    | '/auth'
    | '/share-guest-list'
    | '/settings/members'
    | '/settings/plan-billings'
    | '/messages'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$eventId'
    | '/auth/business-info'
    | '/auth/create-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-reset-password'
    | '/share-guest-list/$eventId'
    | '/'
    | '/auth'
    | '/share-guest-list'
    | '/settings/members'
    | '/settings/plan-billings'
    | '/messages'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$eventId'
    | '/auth/business-info'
    | '/auth/create-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-reset-password'
    | '/share-guest-list/$eventId'
    | '/_authenticated/'
    | '/auth/'
    | '/share-guest-list/'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/plan-billings'
    | '/_authenticated/messages/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthBusinessInfoRoute: typeof AuthBusinessInfoRoute
  AuthCreatePasswordRoute: typeof AuthCreatePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyResetPasswordRoute: typeof AuthVerifyResetPasswordRoute
  ShareGuestListEventIdRoute: typeof ShareGuestListEventIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ShareGuestListIndexRoute: typeof ShareGuestListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-guest-list/': {
      id: '/share-guest-list/'
      path: '/share-guest-list'
      fullPath: '/share-guest-list'
      preLoaderRoute: typeof ShareGuestListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share-guest-list/$eventId': {
      id: '/share-guest-list/$eventId'
      path: '/share-guest-list/$eventId'
      fullPath: '/share-guest-list/$eventId'
      preLoaderRoute: typeof ShareGuestListEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-reset-password': {
      id: '/auth/verify-reset-password'
      path: '/auth/verify-reset-password'
      fullPath: '/auth/verify-reset-password'
      preLoaderRoute: typeof AuthVerifyResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-password': {
      id: '/auth/create-password'
      path: '/auth/create-password'
      fullPath: '/auth/create-password'
      preLoaderRoute: typeof AuthCreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/business-info': {
      id: '/auth/business-info'
      path: '/auth/business-info'
      fullPath: '/auth/business-info'
      preLoaderRoute: typeof AuthBusinessInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$eventId': {
      id: '/_authenticated/$eventId'
      path: '/$eventId'
      fullPath: '/$eventId'
      preLoaderRoute: typeof AuthenticatedEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/plan-billings': {
      id: '/_authenticated/settings/plan-billings'
      path: '/settings/plan-billings'
      fullPath: '/settings/plan-billings'
      preLoaderRoute: typeof AuthenticatedSettingsPlanBillingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEventIdRoute: typeof AuthenticatedEventIdRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsPlanBillingsRoute: typeof AuthenticatedSettingsPlanBillingsRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEventIdRoute: AuthenticatedEventIdRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsPlanBillingsRoute:
    AuthenticatedSettingsPlanBillingsRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthBusinessInfoRoute: AuthBusinessInfoRoute,
  AuthCreatePasswordRoute: AuthCreatePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyResetPasswordRoute: AuthVerifyResetPasswordRoute,
  ShareGuestListEventIdRoute: ShareGuestListEventIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ShareGuestListIndexRoute: ShareGuestListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
